"""empty message

Revision ID: 12d8fabb639f
Revises: fffc78294b86
Create Date: 2022-01-21 18:25:10.489101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d8fabb639f'
down_revision = 'fffc78294b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorisation_block',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('previous_hash', sa.String(length=50), nullable=True),
    sa.Column('property_address', sa.String(length=256), nullable=False),
    sa.Column('approval_status', sa.SmallInteger(), nullable=False),
    sa.Column('hash', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_authorisation_block_previous_hash'), 'authorisation_block', ['previous_hash'], unique=False)
    op.drop_index('ix_authorisation_blocks_previous_hash', table_name='authorisation_blocks')
    op.drop_table('authorisation_blocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorisation_blocks',
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('previous_hash', sa.VARCHAR(length=50), nullable=True),
    sa.Column('property_address', sa.VARCHAR(length=256), nullable=False),
    sa.Column('approval_status', sa.SMALLINT(), nullable=False),
    sa.Column('hash', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index('ix_authorisation_blocks_previous_hash', 'authorisation_blocks', ['previous_hash'], unique=False)
    op.drop_index(op.f('ix_authorisation_block_previous_hash'), table_name='authorisation_block')
    op.drop_table('authorisation_block')
    # ### end Alembic commands ###
