"""empty message

Revision ID: 2436dcd13a2e
Revises: 507738b22890
Create Date: 2022-01-23 14:17:31.387907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2436dcd13a2e'
down_revision = '507738b22890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_finalisation_block',
    sa.Column('hash', sa.String(length=50), nullable=False),
    sa.Column('previous_hash', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('approved', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_sale_finalisation_block_previous_hash'), 'sale_finalisation_block', ['previous_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_finalisation_block_previous_hash'), table_name='sale_finalisation_block')
    op.drop_table('sale_finalisation_block')
    # ### end Alembic commands ###
