"""empty message

Revision ID: 79e7695f9765
Revises: 7a8c03b24f7c
Create Date: 2022-01-21 15:51:22.550361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e7695f9765'
down_revision = '7a8c03b24f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit_application',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('previous_hash', sa.String(length=50), nullable=True),
    sa.Column('property_address', sa.String(length=256), nullable=False),
    sa.Column('seller_details', sa.String(length=256), nullable=False),
    sa.Column('building_design', sa.LargeBinary(), nullable=False),
    sa.Column('seller_licence_number', sa.String(length=23), nullable=False),
    sa.Column('hash', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_permit_application_previous_hash'), 'permit_application', ['previous_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permit_application_previous_hash'), table_name='permit_application')
    op.drop_table('permit_application')
    # ### end Alembic commands ###
