"""empty message

Revision ID: 91caa1348ae6
Revises: f44cb0201c92
Create Date: 2022-01-21 08:57:16.678835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91caa1348ae6'
down_revision = 'f44cb0201c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permit_application', sa.Column('property_address', sa.String(length=256), nullable=False))
    op.add_column('permit_application', sa.Column('building_design', sa.LargeBinary(), nullable=False))
    op.add_column('permit_application', sa.Column('permit_application_id', sa.String(length=23), nullable=False))
    op.add_column('permit_application', sa.Column('seller_details', sa.String(length=256), nullable=False))
    op.add_column('permit_application', sa.Column('seller_licence_number', sa.String(length=23), nullable=False))
    op.drop_column('permit_application', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permit_application', sa.Column('data', sa.BLOB(), nullable=False))
    op.drop_column('permit_application', 'seller_licence_number')
    op.drop_column('permit_application', 'seller_details')
    op.drop_column('permit_application', 'permit_application_id')
    op.drop_column('permit_application', 'building_design')
    op.drop_column('permit_application', 'property_address')
    # ### end Alembic commands ###
