"""empty message

Revision ID: a865841c06bd
Revises: 12d8fabb639f
Create Date: 2022-01-21 23:00:41.645522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a865841c06bd'
down_revision = '12d8fabb639f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_block',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('previous_hash', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('current_address', sa.String(length=256), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=False),
    sa.Column('employer_name', sa.String(length=256), nullable=False),
    sa.Column('annual_income', sa.Numeric(), nullable=False),
    sa.Column('property_address', sa.String(length=256), nullable=False),
    sa.Column('loan_amount', sa.Numeric(), nullable=False),
    sa.Column('hash', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_buyer_block_previous_hash'), 'buyer_block', ['previous_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyer_block_previous_hash'), table_name='buyer_block')
    op.drop_table('buyer_block')
    # ### end Alembic commands ###
