"""empty message

Revision ID: c3de20b2d9a3
Revises: 4d12f6df1078
Create Date: 2022-01-21 08:19:46.813433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3de20b2d9a3'
down_revision = '4d12f6df1078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit_application',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('previous_hash', sa.String(length=512), nullable=True),
    sa.Column('hash', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_permit_application_hash'), 'permit_application', ['hash'], unique=True)
    op.create_index(op.f('ix_permit_application_previous_hash'), 'permit_application', ['previous_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permit_application_previous_hash'), table_name='permit_application')
    op.drop_index(op.f('ix_permit_application_hash'), table_name='permit_application')
    op.drop_table('permit_application')
    # ### end Alembic commands ###
